version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gomod-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gomod"
    directory: "/client-daemon"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gomod-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/web-ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "react"
        versions: [">=19"]
      - dependency-name: "@types/react"
        versions: [">=19"]
    groups:
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      next-react-ecosystem:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
